name    'saz-gearman'
version '2.1.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage gearman job server via Puppet'
project_page 'https://github.com/saz/puppet-gearman'
dependency 'saz/limits', '>= 1.0.0'
